services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    command: npm run dev -- --host 0.0.0.0 --port 3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
